languageCode = "en-us"
title = "Peter"
baseurl = "http://pkoul.com/"
theme = "prologue"

[params]
  name = "Peter Koulouris"
  description = "Artist"
  copyright = "2018"
  logo = "/img/avatar.jpg"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/pkoul/"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/pgkoulouris"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/peter-koulouris-436001109/"